name: My first work
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello all"
  secondjob:
    needs: firstjob
    runs-on: ubuntu-latest
    steps:
      - name: Run multiple commands
        run: |
          echo "Hello Githb"
          echo "my first test job on github action"
